### ISSUE TITLE
上马失败

### ISSUE THREAD

**Issue by Kai5174** [threedr3am/ZhouYu#3]
搭了个测试环境，Tomcat 8， JDK-1.8.0，Linux环境，用Agent上马提示报错

```bash
Exception in thread "main" java.lang.UnsatisfiedLinkError: sun.tools.attach.WindowsVirtualMachine.init()V
        at sun.tools.attach.WindowsVirtualMachine.init(Native Method)
        at sun.tools.attach.WindowsVirtualMachine.<clinit>(WindowsVirtualMachine.java:192)
        at sun.tools.attach.WindowsAttachProvider.attachVirtualMachine(WindowsAttachProvider.java:69)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
        at zhouyu.agent.ZhouYu.main(ZhouYu.java:45)
```

emm 是哪里有问题吗？Tomcat是用tomcat启动的，运行java -jar ZhouYu.jar使用了root权限和tomcat权限，但都报同样错误。

**Comment by Number1loonastan** [comment]
I think you have to using another loader to run + using bitbucket premissions...
